#!/usr/bin/env python3
"""
agent-script/encode-openapi.py

Convert plans/openapi.yaml into a C header that exposes the bytes as a
PROGMEM-friendly uint8_t array. The C preprocessor tokenizes the
contents of any #include'd file (the R""""( )"""" raw-literal trick
only skips string-literal parsing, not general tokenization), so a
YAML file with `3.0.3`, backticks, dashes-as-minus, etc. will fail
to compile if included directly. Encoding the bytes as \\xNN escapes
sidesteps that entirely.

Usage:
    ./agent-script/encode-openapi.py > src/html/openapi_yaml_bytes.h

The generated header defines:
    const uint32_t openapi_yaml_len = N;
    const uint8_t openapi_yaml[] PROGMEM = { 0xNN, 0xNN, ... };

and is meant to be wrapped by src/html.h in a similar way to the
existing R""""( ... )"""" strings:

    const String html_openapi_yaml(openapi_yaml_len,
                                   (const char*)openapi_yaml);

or sent via the len-aware AsyncWebServerRequest::send overload.
"""

import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO_ROOT, "plans", "openapi.yaml")


def main():
    if not os.path.isfile(SRC):
        print(f"FATAL: {SRC} missing", file=sys.stderr)
        sys.exit(2)
    with open(SRC, "rb") as f:
        data = f.read()
    n = len(data)
    print("// Auto-generated by agent-script/encode-openapi.py -- do not edit by hand.")
    print("// Source: plans/openapi.yaml")
    print(f"// Bytes: {n}")
    print("#ifndef RR_OPENAPI_YAML_BYTES_H")
    print("#define RR_OPENAPI_YAML_BYTES_H")
    print("#include <Arduino.h>")
    print()
    print(f"const uint32_t openapi_yaml_len = {n};")
    print(f"const uint8_t openapi_yaml[] PROGMEM = {{")
    # 12 bytes per line is a comfortable column count and matches the
    # width of typical C arrays. Last line has the trailing comma,
    # which C99 allows and the compiler accepts.
    PER_LINE = 12
    for i in range(0, n, PER_LINE):
        chunk = data[i : i + PER_LINE]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        suffix = "," if i + PER_LINE < n else ""
        print(f"    {hexes}{suffix}")
    print("};")
    print()
    print("#endif")
    sys.exit(0)


if __name__ == "__main__":
    main()
